"""
Nifty 500 Stock List
Complete list of all stocks in Nifty 500 index
"""

NIFTY_500_STOCKS = [
    # Nifty 50
    'ADANIENT', 'ADANIPORTS', 'APOLLOHOSP', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJFINANCE', 'BAJAJFINSV',
    'BPCL', 'BHARTIARTL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'EICHERMOT',
    'GRASIM', 'HCLTECH', 'HDFCBANK', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK',
    'ITC', 'INDUSINDBK', 'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI',
    'NTPC', 'NESTLEIND', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE', 'SBIN', 'SUNPHARMA',
    'TCS', 'TATACONSUM', 'TATAMOTORS', 'TATASTEEL', 'TECHM', 'TITAN', 'ULTRACEMCO', 'UPL', 'WIPRO',
    
    # Nifty Next 50
    'ABB', 'ACC', 'AMBUJACEM', 'ADANIGREEN', 'ATGL', 'ALKEM', 'APOLLOTYRE', 'ASHOKLEY', 'AUROPHARMA',
    'DMART', 'BAJAJHLDNG', 'BANDHANBNK', 'BANKBARODA', 'BERGEPAINT', 'BEL', 'BIOCON', 'BOSCHLTD',
    'CANBK', 'CHOLAFIN', 'COLPAL', 'CONCOR', 'COFORGE', 'DABUR', 'DLF', 'DIVISLAB',
    'GAIL', 'GODREJCP', 'GLAND', 'HDFCAMC', 'HAVELLS', 'ICICIPRULI', 'IDEA', 'INDIGO',
    'INDUSTOWER', 'IOC', 'IRCTC', 'IGL', 'JINDALSTEL', 'JUBLFOOD', 'LICHSGFIN', 'LUPIN',
    'MARICO', 'MCDOWELL-N', 'MUTHOOTFIN', 'NMDC', 'NYKAA', 'OFSS', 'PAGEIND', 'PEL',
    'PERSISTENT', 'PETRONET', 'PFC', 'PIDILITIND', 'PNB', 'POLYCAB', 'RECLTD', 'SBICARD',
    'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SRF', 'TATAPOWER', 'TRENT', 'TORNTPHARM', 'TVSMOTOR',
    'UNIONBANK', 'UBL', 'VEDL', 'VOLTAS', 'ZOMATO', 'ZYDUSLIFE',
    
    # Nifty Midcap 150
    'AARTIIND', 'AIAENG', 'AJANTPHARM', 'APLLTD', 'AUBANK', 'AFFLE', 'ABCAPITAL', 'ABFRL',
    'AEGISCHEM', 'AETHER', 'ANGELONE', 'APARINDS', 'ASAHIINDIA', 'ASTRAL', 'ATUL', 'AUROPHARMA',
    'BALKRISIND', 'BALRAMCHIN', 'BATAINDIA', 'BHARATFORG', 'BHEL', 'BSOFT', 'CAMS', 'CANFINHOME',
    'CASTROLIND', 'CEATLTD', 'CENTRALBK', 'CENTURYPLY', 'CERA', 'CHAMBLFERT', 'CHOLAHLDNG', 'CLEAN',
    'COALINDIA', 'COROMANDEL', 'CREDITACC', 'CROMPTON', 'CUB', 'CUMMINSIND', 'CYIENT', 'DEEPAKNTR',
    'DELTACORP', 'DEVYANI', 'DIXON', 'DALBHARAT', 'EIDPARRY', 'ELGIEQUIP', 'EMAMILTD', 'ENDURANCE',
    'ESCORTS', 'EXIDEIND', 'FEDERALBNK', 'FINEORG', 'FINPIPE', 'FLUOROCHEM', 'FORTIS', 'GICRE',
    'GILLETTE', 'GLAXO', 'GLENMARK', 'GMRINFRA', 'GNFC', 'GODFRYPHLP', 'GODREJIND', 'GODREJPROP',
    'GRANULES', 'GRAPHITE', 'GESHIP', 'GSPL', 'GUJGASLTD', 'HAL', 'HAPPSTMNDS', 'HATSUN',
    'HEIDELBERG', 'HEMIPROP', 'HINDCOPPER', 'HINDPETRO', 'HINDZINC', 'HONAUT', 'IBREALEST', 'IDFCFIRSTB',
    'IIFL', 'INDHOTEL', 'INDIANB', 'INDIACEM', 'INDIAMART', 'INDIGOPNTS', 'INDOCO', 'INFIBEAM',
    'INOXWIND', 'INTELLECT', 'IRCON', 'IRFC', 'ISEC', 'ITI', 'J&KBANK', 'JBCHEPHARM',
    'JKCEMENT', 'JKLAKSHMI', 'JKPAPER', 'JMFINANCIL', 'JSL', 'JSWENERGY', 'JUBILANT', 'JUSTDIAL',
    'JYOTHYLAB', 'KANSAINER', 'KEI', 'KFINTECH', 'KPITTECH', 'KRBL', 'L&TFH', 'LALPATHLAB',
    'LAURUSLABS', 'LICI', 'LTIM', 'LTTS', 'LINDEINDIA', 'LXCHEM', 'MANAPPURAM', 'MAPMYINDIA',
    'MASTEK', 'MAXHEALTH', 'MAZDOCK', 'METROBRAND', 'METROPOLIS', 'MFSL', 'MGL', 'MHRIL',
    'MIDHANI', 'MOTILALOFS', 'MOTHERSON', 'MPHASIS', 'MRF', 'MRPL', 'MSUMI', 'NATCOPHARM',
    'NATIONALUM', 'NAUKRI', 'NAVINFLUOR', 'NBCC', 'NCC', 'NETWORK18', 'NLCINDIA', 'NMDC',
    'OBEROIRLTY', 'OIL', 'OLECTRA', 'PAYTM', 'PCBL', 'PERSISTENT', 'PETRONET', 'PFIZER',
    'PGHH', 'PHOENIXLTD', 'PIRAMALENT', 'PIIND', 'PNB', 'PNBHOUSING', 'POLICYBZR', 'POLYMED',
    'POWERGRID', 'PRAJIND', 'PRESTIGE', 'PRINCEPIPE', 'PRSMJOHNSN', 'PVRINOX', 'QUESS', 'RADICO',
    'RAIN', 'RAJESHEXPO', 'RALLIS', 'RAMCOCEM', 'RATNAMANI', 'RAYMOND', 'RBL', 'REDINGTON',
    'RELAXO', 'ROUTE', 'RVNL', 'SAIL', 'SANOFI', 'SCHAEFFLER', 'SCHNEIDER', 'SHARDACROP',
    'SHILPAMED', 'SIS', 'SJVN', 'SKFINDIA', 'SOBHA', 'SOLARINDS', 'SONACOMS', 'SONATSOFTW',
    'STARHEALTH', 'STLTECH', 'SUDARSCHEM', 'SUMICHEM', 'SUNDARMFIN', 'SUNDRMFAST', 'SUNTV', 'SUPREMEIND',
    'SUVENPHAR', 'SWANENERGY', 'SYMPHONY', 'SYNGENE', 'TATACHEM', 'TATACOMM', 'TATAELXSI', 'TATAINVEST',
    'TATATECH', 'TEAMLEASE', 'TECHM', 'THERMAX', 'THYROCARE', 'TIMKEN', 'TITAGARH', 'TORNTPOWER',
    'TRENT', 'TRIDENT', 'TRITURBINE', 'TUBE', 'TV18BRDCST', 'TVSMOTOR', 'UCOBANK', 'UJJIVAN',
    'ULTRACEMCO', 'UNIONBANK', 'UPL', 'UTIAMC', 'VAIBHAVGBL', 'VARROC', 'VBL', 'VEDL',
    'VENKEYS', 'VESUVIUS', 'VIJAYA', 'VINATIORGA', 'VIPIND', 'VMART', 'VOLTAMP', 'VOLTAS',
    'VTL', 'WABAG', 'WELCORP', 'WELSPUNIND', 'WESTLIFE', 'WHIRLPOOL', 'WIPRO', 'WOCKPHARMA',
    'YESBANK', 'ZEEL', 'ZENSARTECH', 'ZOMATO', 'ZYDUSLIFE', 'ZYDUSWELL',
    
    # Additional Nifty 500 stocks
    '3MINDIA', '8KMILES', 'AAVAS', 'ACE', 'ADANIENSOL', 'ADANIGAS', 'ADANIPOWER', 'ADANITRANS',
    'ADVENZYMES', 'AEGISLOG', 'AFFLE', 'AGARIND', 'AGROPHOS', 'AHLEAST', 'AHLUCONT', 'AIAENG',
    'AIROLAM', 'AJMERA', 'AKZOINDIA', 'ALEMBICLTD', 'ALKYLAMINE', 'ALLCARGO', 'AMARAJABAT', 'AMBER',
    'AMBUJACEM', 'AMIORG', 'ANANTRAJ', 'ANDHRSUGAR', 'ANGELONE', 'ANIKINDS', 'ANURAS', 'APCOTEXIND',
    'APLAPOLLO', 'APOLLOPIPE', 'ARVINDFASN', 'ARVIND', 'ASALCBR', 'ASHIANA', 'ASHOKLEY', 'ASIANHOTNR',
    'ASTERDM', 'ASTRAMICRO', 'ASTRAZEN', 'ATFL', 'ATLANTA', 'ATULAUTO', 'AUSOMENT', 'AVANTIFEED',
    'AXISCADES', 'BALAXI', 'BALAMINES', 'BALMLAWRIE', 'BANCOINDIA', 'BASF', 'BAYERCROP', 'BEML',
    'BFUTILITIE', 'BGRENERGY', 'BHARATGEAR', 'BHARATRAS', 'BHARATWIRE', 'BHEL', 'BIRLACORPN', 'BIRLAMONEY',
    'BLISSGVS', 'BLKASHYAP', 'BLS', 'BLUEDART', 'BLUESTARCO', 'BOMDYEING', 'BRIGADE', 'BRITANNIA',
    'BSOFT', 'BURGERKING', 'BUTTERFLY', 'CADILAHC', 'CAMPUS', 'CAPLIPOINT', 'CARBORUNIV', 'CARERATING',
    'CARYSIL', 'CCL', 'CEATLTD', 'CENTENKA', 'CENTRALBK', 'CENTRUM', 'CENTURYTEXT', 'CERA',
    'CHALET', 'CHAMBLFERT', 'CHEMPLASTS', 'CHENNPETRO', 'CHOLAHLDNG', 'CIEINDIA', 'CIGNITITEC', 'CIPLA',
    'CLEDUCATE', 'COALINDIA', 'COCHINSHIP', 'COFORGE', 'COLPAL', 'COMPINFO', 'CONCOR', 'COROMANDEL',
    'COSMOFIRST', 'CRAFTSMAN', 'CREDITACC', 'CRISIL', 'CROMPTON', 'CUB', 'CUMMINSIND', 'CUPID',
    'CYIENT', 'DAAWAT', 'DABUR', 'DALBHARAT', 'DATAMATICS', 'DBCORP', 'DBL', 'DCAL',
    'DCB', 'DCBBANK', 'DCM', 'DCMSHRIRAM', 'DCXINDIA', 'DEEPAKFERT', 'DEEPAKNTR', 'DELTACORP',
    'DEN', 'DHANUKA', 'DHANI', 'DHUNINV', 'DISHTV', 'DIVISLAB', 'DIXON', 'DLF',
    'DMART', 'DOLLAR', 'DONEAR', 'DPWIRES', 'DRREDDY', 'DREDGECORP', 'DRREDDY', 'DUCON',
    'DWARIKESH', 'DYNAMATECH', 'EASEMYTRIP', 'EDELWEISS', 'EDUCOMP', 'EICHERMOT', 'EIDPARRY', 'EIHOTEL',
    'ELECON', 'ELGIEQUIP', 'EMAMILTD', 'EMAMIPAP', 'ENDURANCE', 'ENERGYDEV', 'ENGINERSIN', 'ENIL',
    'EPL', 'EQUITAS', 'ERIS', 'EROSMEDIA', 'ESABINDIA', 'ESCORTS', 'ESSARSHPNG', 'ESTER',
    'EUROTEXIND', 'EVEREADY', 'EXCELINDUS', 'EXIDEIND', 'FACT', 'FAIRCHEMOR', 'FCL', 'FEDERALBNK',
    'FEL', 'FIEMIND', 'FILATEX', 'FINCABLES', 'FINEORG', 'FINPIPE', 'FIRSTCRY', 'FIVESTAR',
    'FLUOROCHEM', 'FORCEMOT', 'FORTIS', 'FOSECOIND', 'FSL', 'GABRIEL', 'GAEL', 'GAIL',
    'GALAXYSURF', 'GANESHHOUC', 'GARFIBRES', 'GATEWAY', 'GEECEE', 'GENUSPOWER', 'GEOJITFSL', 'GEPIL',
    'GESHIP', 'GET&D', 'GHCL', 'GICHSGFIN', 'GICRE', 'GILLETTE', 'GINNIFILA', 'GIPCL',
    'GLAND', 'GLAXO', 'GLENMARK', 'GLOBALVECT', 'GLOBE', 'GLOBUSSPR', 'GLS', 'GMBREW',
    'GMMPFAUDLR', 'GMRINFRA', 'GNA', 'GNFC', 'GOACARBON', 'GOCLCORP', 'GODFRYPHLP', 'GODREJAGRO',
    'GODREJCP', 'GODREJIND', 'GODREJPROP', 'GOKEX', 'GOKUL', 'GOLDIAM', 'GOLDENTOBC', 'GOODLUCK',
    'GOODYEAR', 'GPIL', 'GPPL', 'GRANULES', 'GRAPHITE', 'GRASIM', 'GRAVITA', 'GREAVESCOT',
    'GREENLAM', 'GREENPLY', 'GREENPOWER', 'GRINDWELL', 'GRSE', 'GRUH', 'GSFC', 'GSHIP',
    'GSS', 'GTLINFRA', 'GTPL', 'GUFICBIO', 'GUJALKALI', 'GUJAPOLLO', 'GUJGASLTD', 'GUJNREDWTR',
    'GULFOILLUB', 'HAL', 'HAPPSTMNDS', 'HARIOMPIPE', 'HARRMALAYA', 'HATHWAY', 'HATSUN', 'HAVELLS',
    'HCC', 'HCG', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE', 'HEG', 'HEIDELBERG',
    'HERANBA', 'HERITGFOOD', 'HEROMOTOCO', 'HESTERBIO', 'HEUBACHIND', 'HEXAWARE', 'HFCL', 'HGINFRA',
    'HIKAL', 'HIL', 'HIMATSEIDE', 'HINDALCO', 'HINDCOPPER', 'HINDNATGLS', 'HINDOILEXP', 'HINDPETRO',
    'HINDUNILVR', 'HINDZINC', 'HIRECT', 'HISARMETAL', 'HITECHCORP', 'HITECHGEAR', 'HLEGLAS', 'HMT',
    'HMVL', 'HOMEFIRST', 'HONAUT', 'HPAL', 'HSCL', 'HTMEDIA', 'HUDCO', 'HUHTAMAKI'
]

# Sector-wise classification
NIFTY_500_SECTORS = {
    'Technology': ['TCS', 'INFY', 'WIPRO', 'HCLTECH', 'TECHM', 'LTIM', 'LTTS', 'MPHASIS', 'PERSISTENT', 
                   'COFORGE', 'TATAELXSI', 'CYIENT', 'SONATSOFTW', 'MASTEK', 'KPITTECH', 'INTELLECT',
                   'HAPPSTMNDS', 'ZENSARTECH', 'BSOFT', 'HEXAWARE', 'CIGNITITEC', 'ROUTE'],
    
    'Banking': ['HDFCBANK', 'ICICIBANK', 'SBIN', 'KOTAKBANK', 'AXISBANK', 'INDUSINDBK', 'FEDERALBNK',
                'BANDHANBNK', 'AUBANK', 'RBLBANK', 'IDFCFIRSTB', 'CANBK', 'PNB', 'BANKBARODA', 'UNIONBANK',
                'INDIANB', 'CENTRALBK', 'J&KBANK', 'UCOBANK', 'YESBANK', 'DCB', 'DCBBANK', 'CUB'],
    
    'Auto': ['TATAMOTORS', 'M&M', 'MARUTI', 'EICHERMOT', 'HEROMOTOCO', 'BAJAJ-AUTO', 'TVSMOTOR',
             'ESCORTS', 'ASHOKLEY', 'MOTHERSON', 'APOLLOTYRE', 'MRF', 'CEATLTD', 'BALKRISIND',
             'EXIDEIND', 'AMARAJABAT', 'ENDURANCE', 'BHARATFORG', 'MSUMI', 'BOSCHLTD', 'SCHAEFFLER'],
    
    'Pharma': ['SUNPHARMA', 'DIVISLAB', 'DRREDDY', 'CIPLA', 'BIOCON', 'TORNTPHARM', 'LUPIN', 'AUROPHARMA',
               'ALKEM', 'GLAND', 'LAURUSLABS', 'NATCOPHARM', 'GRANULES', 'GLENMARK', 'AJANTPHARM',
               'SYNGENE', 'LALPATHLAB', 'METROPOLIS', 'THYROCARE', 'APOLLOHOSP', 'MAXHEALTH', 'FORTIS'],
    
    'FMCG': ['HINDUNILVR', 'ITC', 'NESTLEIND', 'BRITANNIA', 'DABUR', 'MARICO', 'COLPAL', 'GODREJCP',
             'TATACONSUM', 'EMAMILTD', 'JYOTHYLAB', 'VBL', 'RADICO', 'MCDOWELL-N', 'UBL', 'GILLETTE',
             'BATAINDIA', 'GODFRYPHLP', 'PGHH', 'PRSMJOHNSN', 'HATSUN', 'HERITGFOOD'],
    
    'Metals': ['TATASTEEL', 'JSWSTEEL', 'HINDALCO', 'VEDL', 'SAIL', 'NMDC', 'HINDZINC', 'NATIONALUM',
               'JINDALSTEL', 'JSL', 'HINDCOPPER', 'RATNAMANI', 'APL', 'WELSPUNIND', 'JKLAKSHMI'],
    
    'Energy': ['RELIANCE', 'ONGC', 'BPCL', 'IOC', 'GAIL', 'PETRONET', 'NTPC', 'POWERGRID', 'COALINDIA',
               'ADANIGREEN', 'ADANIPOWER', 'TATAPOWER', 'TORNTPOWER', 'SJVN', 'NHPC', 'OIL', 'HINDPETRO'],
    
    'Finance': ['BAJFINANCE', 'BAJAJFINSV', 'CHOLAFIN', 'MUTHOOTFIN', 'SHRIRAMFIN', 'PFC', 'RECLTD',
                'LICHSGFIN', 'SBICARD', 'HDFCAMC', 'HDFCLIFE', 'SBILIFE', 'ICICIPRULI', 'STARHEALTH',
                'MANAPPURAM', 'IIFL', 'MFSL', 'MOTILALOFS', 'ANGELONE', 'POLICYBZR', 'CREDITACC'],
    
    'Realty': ['DLF', 'GODREJPROP', 'OBEROIRLTY', 'PRESTIGE', 'BRIGADE', 'SOBHA', 'PHOENIXLTD',
               'IBREALEST', 'MAHLIFE', 'LODHA', 'SUNTECK', 'ASHIANA'],
    
    'Cement': ['ULTRACEMCO', 'SHREECEM', 'AMBUJACEM', 'ACC', 'DALMIA', 'RAMCOCEM', 'JKCEMENT',
               'HEIDELBERG', 'BIRLACEM', 'STARCEMENT', 'ORIENTCEM']
}
